services:
  redis:
    image: redis:8.6.2
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass your_secure_password
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: database
    volumes:
      - mongo-data:/data/db
  postgres:
    image: postgres:14.22-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mysqldb:
    image: mysql:8.4 # Using LTS version for 2026 stability
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
  mongo-data:
  postgres_data:
  redis_data: